apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
  namespace: my-namespace
  labels:
    app: food-app
  annotations:
    createdby: "Rajkumar Nanchari"
    description: "This application is done by Arun kumar Akula"
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec: 
      containers:
        - name: food-application
          image: arun3647/food-app
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: food-app-service
  namespace: my-namespace
  labels:
    app: food-app
spec:
  selector:
    app: food-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer    
  